name: cook_assistant
description: "cook_assistant application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^3.0.0
  flutter_svg: ^2.0.10+1
  
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  flutter_login: ^4.1.1
  image_picker: ^1.1.1
  intl: ^0.17.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  permission_handler: ^11.3.1
  flutter_sound: ^9.3.3
  
flutter:
  uses-material-design: true

  assets:
    - assets/banners/
    - assets/icons/
    - assets/images/
    - assets/config/
    - assets/service_account.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image assets can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the assets and other descriptors for the font.
  # Example commented out below:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - assets: fonts/Schyler-Regular.ttf
  #       - assets: fonts/Schyler-Italic.ttf
  #         style: italic
